### ISSUE TITLE
Could not install on my ubuntu 18.04

### ISSUE THREAD

**Issue by felixfi** [airbus/scikit-decide#20]
## 🐛 Bug

pip install .[all]

fails

`Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 113.3 MB/s 
Building wheels for collected packages: scikit-decide, gym, future, gpustat, nvidia-ml-py3, pyrsistent
  Building wheel for scikit-decide (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/felix/anaconda3/envs/skdecide/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0omxnjg4/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0omxnjg4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0nb0xxs9
       cwd: /tmp/pip-req-build-0omxnjg4/
  Complete output (13 lines):
  version: 0.9.1-11-g63396a1
  linux
  Linux ['gym>=0.13.0', 'joblib>=0.13.2', 'numpy>=1.16.4', 'matplotlib>=3.1.0', 'pathos>=0.2.3', 'pynng>=0.5.0', 'ray[rllib,debug]>=1.0.0', 'simplejson>=3.16.0', 'stable-baselines3[extra]>=0.9.0', "torch==1.6.0; sys_platform == 'darwin'"]
  Linux ['pytest', 'pytest-cov', 'simplejson', 'tqdm', 'wheel']
  Linux {'domains': ['gym>=0.13.0', 'numpy>=1.16.4', 'matplotlib>=3.1.0', 'simplejson>=3.16.0'], 'solvers': ['gym>=0.13.0', 'numpy>=1.16.4', 'joblib>=0.13.2', 'ray[rllib,debug]>=1.0.0', 'torch==1.6.0', 'stable-baselines3>=0.9.0'], 'all': ['gym>=0.13.0', 'numpy>=1.16.4', 'matplotlib>=3.1.0', 'simplejson>=3.16.0', 'gym>=0.13.0', 'numpy>=1.16.4', 'joblib>=0.13.2', 'ray[rllib,debug]>=1.0.0', 'torch==1.6.0', 'stable-baselines3>=0.9.0']}
  /home/felix/anaconda3/envs/skdecide/lib/python3.7/site-packages/setuptools/dist.py:479: UserWarning: The version specified ('0.9.1-11-g63396a1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
    "details." % version
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: option -d not recognized
  ----------------------------------------
  ERROR: Failed building wheel for scikit-decide
`

**Comment by galleon** [comment]
Thanks at @felixfi. Indeed it is a know issue. On this release, `pip install .` is not working. `python setup.py bdist_wheel --cpp-extension` should do the job.

**Comment by felixfi** [comment]
`(skdecide) felix@counterpart:~/work/scikit-decide$ python setup.py bdist_wheel --cpp-extension`

prodiuces later:
```
Scanning dependencies of target __skdecide_hub_cpp
[ 91%] Building CXX object src/hub/CMakeFiles/__skdecide_hub_cpp.dir/py_skdecide.cc.o
[ 92%] Building CXX object src/hub/CMakeFiles/__skdecide_hub_cpp.dir/solver/py_astar.cc.o
In file included from /home/felix/work/scikit-decide/cpp/src/utils/python_hash_eq.hh:16:0,
                 from /home/felix/work/scikit-decide/cpp/src/hub/solver/py_astar.cc:13:
/home/felix/work/scikit-decide/cpp/src/utils/python_container_adapter.hh:11:10: fatal error: boost/container_hash/hash.hpp: No such file or directory
 #include <boost/container_hash/hash.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/hub/CMakeFiles/__skdecide_hub_cpp.dir/build.make:92: recipe for target 'src/hub/CMakeFiles/__skdecide_hub_cpp.dir/solver/py_astar.cc.o' failed
make[2]: *** [src/hub/CMakeFiles/__skdecide_hub_cpp.dir/solver/py_astar.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1694: recipe for target 'src/hub/CMakeFiles/__skdecide_hub_cpp.dir/all' failed
make[1]: *** [src/hub/CMakeFiles/__skdecide_hub_cpp.dir/all] Error 2
Makefile:168: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 286, in <module>
    cmdclass=dict(build_ext=CMakeBuild, install=InstallCommand, bdist_wheel=BDistWheelCommand)
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 63, in run
    bdist_wheel.run(self)
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 132, in run
    self.build_extension(ext)
  File "setup.py", line 166, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/felix/anaconda3/envs/skdecide/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.

```

**Comment by fteicht** [comment]
Hi @felixfi you should indeed install boost's development files. On ubuntu you can install them with the following command: `sudo apt-get install libboost-all-dev`

**Comment by galleon** [comment]
Closing as agreed. @fteicht to check with @felixfi the status on latest release.
