### ISSUE TITLE
Failed to install scikit-decide pip package

### ISSUE THREAD

**Issue by Timmifixedit** [airbus/scikit-decide#222]
## 🐛 Bug

I am unable to install the scikit-decide pip package following the provided installation instructions. I'm running Ubuntu 22.04 LTS, Python 3.10.6 and pip 22.0.2. Minizinc is installed on my system and is added to the PATH variable.

## To Reproduce

1. set up virtual env: `python3 -m venv venv && source venv/bin/activate`
2. update pip `pip install -U pip`
3. install scikit-decide package `pip install -U scikit-decide`

The following error is reported by pip:
```
~ » pip install -U scikit-decide
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting scikit-decide
  Downloading scikit-decide-0.9.1.tar.gz (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.3/76.3 kB 930.1 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4xwzym07/scikit-decide_8da19f2f77cf41308e8a0e737f08eece/setup.py", line 14, in <module>
          from wheel.bdist_wheel import bdist_wheel
      ModuleNotFoundError: No module named 'wheel'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
If I install `wheel` and try to install `scikit-decide` again, another error occurs:
```
~ » pip install -U wheel
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.37.1
(venv) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~ » pip install -U scikit-decide
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting scikit-decide
  Downloading scikit-decide-0.9.1.tar.gz (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.3/76.3 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-okih4tol/scikit-decide_89315d7656674f588833b909e02b5a3a/setup.py", line 31, in <module>
          version = _get_version_hash()
        File "/tmp/pip-install-okih4tol/scikit-decide_89315d7656674f588833b909e02b5a3a/setup.py", line 25, in _get_version_hash
          ver = subprocess.check_output(["git", "describe", "--tags", "--always"], encoding="utf-8")
        File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--always']' returned non-zero exit status 128.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

## Expected behavior

The package should install correctly.

## Environment
This is the virtual environment created for reproducing this problem:
```
~/scikit-decide (master) » python utils/collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] Could not collect
[conda] Could not collect

Skdecide version: Not available

```
This is the virtual environment in which I try to install the scikit-decide package
```
» python utils/collect_env.py 
Collecting environment information...
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.13.0
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.1.0.post1
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.15
[pip3] torch-spline-conv==1.2.1
[conda] Could not collect

Skdecide version: Not available

```

**Comment by nhuet** [comment]
This issue seems to be solved in more recent versions of pip and scikit-decide.
The install is ok with python 3.10.11 + pip 23.2.1 + scikit-decide 0.9.7
We should be able to close this issue.

However , you may encounter issues when installing extra dependencies with `pip install scikit-decide[all]` because of an issue with gym==0.21.0. See https://airbus.github.io/scikit-decide/install.html#troubleshooting for more information about a work around, while expecting the integration of gymnasium to come.
